package be.blop.libcap.linux;

public interface SecureBits {
	int SECURE_NOROOT = 0;
	int SECURE_NOROOT_LOCKED = 1;
	int SECURE_NO_SETUID_FIXUP = 2;
	int SECURE_NO_SETUID_FIXUP_LOCKED = 3;
	int SECURE_KEEP_CAPS = 4;
	int SECURE_KEEP_CAPS_LOCKED = 5;

	int SECUREBITS_DEFAULT = 0x00000000;
	int SECBIT_NOROOT = (1 << SECURE_NOROOT);
	int SECBIT_NOROOT_LOCKED = (1 << (SECURE_NOROOT_LOCKED));
	int SECBIT_NO_SETUID_FIXUP = (1 << (SECURE_NO_SETUID_FIXUP));
	int SECBIT_NO_SETUID_FIXUP_LOCKED = (1 << (SECURE_NO_SETUID_FIXUP_LOCKED));
	int SECBIT_KEEP_CAPS = (1 << (SECURE_KEEP_CAPS));
	int SECBIT_KEEP_CAPS_LOCKED = (1 << (SECURE_KEEP_CAPS_LOCKED));
	int SECURE_ALL_BITS = (1 << (SECURE_NOROOT) | 1 << (SECURE_NO_SETUID_FIXUP) | 1 << (SECURE_KEEP_CAPS));
	int SECURE_ALL_LOCKS = (SECURE_ALL_BITS << 1);
}